config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :wikis

  get 'about' => 'welcome#about'  

  root to: 'welcome#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis, dependent: :destroy



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end

  def moderator?
    role == 'moderator'
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  mount_uploader :picture, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.all
    authorize @wikis
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    authorize @wiki
      
      if @wiki.save
        redirect_to @wiki, notice: "Commence New Wiki."
      else
        flash[:error] = "Error creating Wiki. Try again."
        render :new
      end
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
      if @wiki.update_attributes(wiki_params)
        redirect_to @wiki
      else
        flash[:error] = "Error saving wiki. Try again."
        render :edit
      end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    title = @wiki.title
    if @wiki.destroy
      flash[:notice] = "\"#{title}\" was successfully deleted."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :description, :picture, :picture_cache, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Jennpedia</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%=link_to "About", about_path %></li>
        <% if current_user %>
          <li><%= link_to "Wikis", wikis_path %></li>
          <li><%= link_to "New", new_wiki_path %></li>
        <% end %>
        </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user%>
          <li><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %><li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jennpedia</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render partial: "layouts/navbar" %>
    
<%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Jennpedia</h1>
<h2>Created by: Jesse Jennings</h2>

app/views/welcome/index.html.erb
<div class="header">
  <h1>Jennpedia</h1>
  <h2>Create and edit your own wikis</h2>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<%= form_for [@wiki], multipart: true do |f| %>
<%= f.hidden_field :picture_cache %>
<%= f.file_field :picture %>
<br>
  <div>
    <div class="form-group"><%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group"><%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group"><%= f.check_box :private %>
      <%= f.label :private? %>
    </div>
     <div class="submit"><%= f.submit %>
     </div>
</div>
<% end %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if policy(Wiki.new).create? %>
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<%= form_for [@wiki], multipart: true do |f| %>
<%= f.hidden_field :picture_cache %>
<%= f.file_field :picture %>

  <div>
    <div class="form-group"><%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group"><%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group"><%= f.check_box :private %>
      <%= f.label :private? %>
    </div>
     <div class="submit"><%= f.submit %>
     </div>
</div>
<% end %>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
  <%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-success" %>
  <% end %>

  <p><%= markdown_to_html @wiki.body %></p>